version: '3.8'

services:
  photography-portfolio-app:
    # Use the image you built locally with 'docker build -t photography-portfolio-dev .'
    image: localhost/photography-portfolio-dev:latest
    
    # Map the container port 5173 to the host machine port 5173
    ports:
      - "5173:5173"
      
    # Environment variables
    environment:
      - NODE_ENV=development

    # Set the restart policy to ensure the container restarts if it crashes
    restart: unless-stopped
    
    # You must expose the server by telling it to bind to 0.0.0.0
    command: npm run docker:dev -- --host