version: '3.8'

services:
  photography-portfolio-app:
    # Use the image you built locally with 'docker build -t photo-gallery-dev .'
    image: photo-gallery-dev:latest
    
    # Map the container port 5173 to the host machine port 5173
    ports:
      - "5173:5173"
      
    # Environment variables
    environment:
      - NODE_ENV=development

    # Set the restart policy to ensure the container restarts if it crashes
    restart: unless-stopped
    
    # You can optionally rely on the CMD in the Dockerfile, or uncomment this 
    # to explicitly run the combined script.
    # command: npm run docker:dev